// Folder names the app recognises as languages, and their codes. Add a line for a language that is missing, or put a
// file language.txt containing  code: xx  inside the language's folder instead. One "Name": "code" per line.
const LANGUAGE_NAMES = {
  "English": "en",
  "Español": "es",
  "Spanish": "es",
  "Español (México)": "es-MX",
  "Français": "fr",
  "French": "fr",
  "Deutsch": "de",
  "German": "de",
  "Italiano": "it",
  "Italian": "it",
  "Português": "pt",
  "Portuguese": "pt",
  "Português (Brasil)": "pt-BR",
  "Nederlands": "nl",
  "Dutch": "nl",
  "Svenska": "sv",
  "Swedish": "sv",
  "Norsk": "nb",
  "Norwegian": "nb",
  "Dansk": "da",
  "Danish": "da",
  "Suomi": "fi",
  "Finnish": "fi",
  "Polski": "pl",
  "Polish": "pl",
  "Čeština": "cs",
  "Czech": "cs",
  "Magyar": "hu",
  "Hungarian": "hu",
  "Română": "ro",
  "Romanian": "ro",
  "Български": "bg",
  "Bulgarian": "bg",
  "Ελληνικά": "el",
  "Greek": "el",
  "Русский": "ru",
  "Russian": "ru",
  "Українська": "uk",
  "Ukrainian": "uk",
  "Türkçe": "tr",
  "Turkish": "tr",
  "עברית": "he",
  "Hebrew": "he",
  "العربية": "ar",
  "Arabic": "ar",
  "فارسی": "fa",
  "Persian": "fa",
  "Farsi": "fa",
  "हिन्दी": "hi",
  "Hindi": "hi",
  "বাংলা": "bn",
  "Bengali": "bn",
  "اردو": "ur",
  "Urdu": "ur",
  "தமிழ்": "ta",
  "Tamil": "ta",
  "తెలుగు": "te",
  "Telugu": "te",
  "मराठी": "mr",
  "Marathi": "mr",
  "中文": "zh-Hans",
  "Chinese": "zh-Hans",
  "Mandarin": "zh-Hans",
  "普通话": "zh-Hans",
  "简体中文": "zh-Hans",
  "繁體中文": "zh-Hant",
  "Cantonese": "yue",
  "粵語": "yue",
  "日本語": "ja",
  "Japanese": "ja",
  "한국어": "ko",
  "Korean": "ko",
  "Tiếng Việt": "vi",
  "Vietnamese": "vi",
  "ไทย": "th",
  "Thai": "th",
  "Bahasa Indonesia": "id",
  "Indonesian": "id",
  "Bahasa Melayu": "ms",
  "Malay": "ms",
  "Filipino": "fil",
  "Tagalog": "tl",
  "Kiswahili": "sw",
  "Swahili": "sw",
  "Català": "ca",
  "Catalan": "ca",
  "Euskara": "eu",
  "Basque": "eu",
  "Galego": "gl",
  "Galician": "gl",
  "Náhuatl": "nah",
  "Nahuatl": "nah",
  "Maya": "yua",
  "Yucatec Maya": "yua",
  "Quechua": "qu",
  "Guaraní": "gn",
  "Guarani": "gn"
};
