# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Teo Monroy
"""Dump every genus paragraph next to the four bits that select it, so the text can be read
against the logic. Reads the app's own tables; re-implements nothing.

usage (repository root):  python3 tests/audit/probe_genus_text.py
writes out/audit/genus_text.md  and prints its path.

Bit order in a genus id is B,P,S,F:
  B  1 = wide (kept forms spread over several unrelated fields)   0 = focused
  P  1 = planned, repeatable                                      0 = improvised
  S  1 = works with other people                                  0 = works alone
  F  1 = open to interpretation                                   0 = literal / functional
"""
import json, pathlib
from playwright.sync_api import sync_playwright

ROOT = pathlib.Path(__file__).resolve().parents[2]
MEAN = {"B": ("wide", "focused"), "P": ("planned", "improvised"), "S": ("works with others", "works alone"),
        "F": ("open to interpretation", "literal or functional")}

with sync_playwright() as pw:
    br = pw.chromium.launch(); pg = br.new_page()
    pg.goto((ROOT / "index.html").as_uri()); pg.wait_for_timeout(1000)
    data = pg.evaluate("""() => {
      const g = typeof GENUS_TABLE !== 'undefined' ? GENUS_TABLE : null;
      const r = typeof REGIME_LEVELS !== 'undefined' ? REGIME_LEVELS : null;
      return { genus: g ? Object.fromEntries(Object.entries(g).map(([k, v]) => [k, { name: v.name, text: v.text }])) : null,
               regime: r ? JSON.parse(JSON.stringify(r)) : null };
    }""")
    br.close()

if not data["genus"]:
    raise SystemExit("GENUS_TABLE is not reachable as a global; open src/model/classification.js and find the table's real name")
out = ["# Genus paragraphs next to their bits (generated by probe_genus_text.py)", "",
       "A bit digit of 1 means the first word in each pair below, 0 means the second.", ""]
for key in sorted(data["genus"]):
    g = data["genus"][key]
    decoded = "; ".join("%s = %s" % (b, MEAN[b][0] if key[i] == "1" else MEAN[b][1]) for i, b in enumerate("BPSF"))
    sentences = [s.strip() for s in g["text"].replace("? ", "?|").replace(". ", ".|").split("|") if s.strip()]
    out += ["## %s  %s" % (key, g["name"]), "bits: " + decoded, ""]
    out += ["%d. %s" % (i + 1, s) for i, s in enumerate(sentences)] + [""]
if data["regime"]:
    out += ["## Regimes (the fifth reading, shown next to the genus)", "", json.dumps(data["regime"], indent=1)[:3000], ""]
p = ROOT / "out" / "audit"; p.mkdir(parents=True, exist_ok=True)
(p / "genus_text.md").write_text("\n".join(out), encoding="utf-8")
print("wrote out/audit/genus_text.md  (%d genera)" % len(data["genus"]))
